import {
  Home,
  Utensils,
  Car,
  HeartPulse,
  PartyPopper,
  GraduationCap,
  ShoppingCart,
  Banknote,
  Shapes,
  Wifi,
  Shirt,
  Dog,
  Plane,
  Gift,
  Fuel,
  Dumbbell,
  Baby,
  Wrench,
  Smartphone,
  Tv,
  Landmark,
  PiggyBank,
  Briefcase,
  Coffee,
  Film,
  Pill,
  Zap,
  Droplet,
  type LucideIcon,
} from "lucide-react"

export const ICONS: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  car: Car,
  "heart-pulse": HeartPulse,
  "party-popper": PartyPopper,
  "graduation-cap": GraduationCap,
  "shopping-cart": ShoppingCart,
  banknote: Banknote,
  shapes: Shapes,
  wifi: Wifi,
  shirt: Shirt,
  dog: Dog,
  plane: Plane,
  gift: Gift,
  fuel: Fuel,
  dumbbell: Dumbbell,
  baby: Baby,
  wrench: Wrench,
  smartphone: Smartphone,
  tv: Tv,
  landmark: Landmark,
  "piggy-bank": PiggyBank,
  briefcase: Briefcase,
  coffee: Coffee,
  film: Film,
  pill: Pill,
  zap: Zap,
  droplet: Droplet,
}

export const ICON_NAMES = Object.keys(ICONS)

export function getCategoryIcon(name: string): LucideIcon {
  return ICONS[name] ?? Shapes
}
